from __future__ import annotations

APP_META = {
    "appName": "AzurJuus//",
    "suiteLabel": "Multi-Agent Social Workspace",
    "version": "0.5.0",
}

DEFAULT_CHARACTERS = ["标枪", "绫波", "Z23", "拉菲"]

DEFAULT_USER = {
    "id": "commander",
    "name": "指挥官",
    "handle": "@commander",
    "faction": "港区司令部",
    "status": "在线",
    "initials": "CM",
    "palette": ["#5c89ff", "#7fe1ff"],
    "accent": "#85ddff",
    "favorite": False,
    "capabilities": ["协调"],
    "tools": ["message.send", "workflow.dispatch", "approval.review"],
}

DEFAULT_SETTINGS = {
    "resolutionPreset": "balanced",
    "maxConnectedAgents": len(DEFAULT_CHARACTERS),
    "connectedAgentIds": [],
    "characterRosterText": "\n".join(DEFAULT_CHARACTERS),
    "llmProvider": "OpenAI Compatible",
    "llmModel": "gpt-4.1-mini",
    "llmBaseUrl": "https://api.openai.com/v1",
    "llmApiKey": "",
    "toolProfile": "local-python",
    "toolBaseUrl": "http://127.0.0.1:8000",
    "toolApiKey": "",
    "authorizedWorkspaceRoot": "",
    "secretaryAgentId": "",
    "allowIdleSocial": True,
    "socialIntervalMinutes": 60,
}

WALLPAPERS = [
    {
        "id": "polar-bloom",
        "name": "极地晶花",
        "surface": "rgba(255, 255, 255, 0.56)",
        "veil": "radial-gradient(circle at 16% 18%, rgba(120, 219, 255, 0.36), transparent 26%), radial-gradient(circle at 70% 22%, rgba(255, 255, 255, 0.48), transparent 28%), radial-gradient(circle at 40% 74%, rgba(164, 196, 255, 0.24), transparent 28%)",
        "accent": "#72d7ff",
        "bubble": "rgba(255, 255, 255, 0.82)",
    },
    {
        "id": "harbor-lounge",
        "name": "港区午后",
        "surface": "rgba(255, 250, 247, 0.56)",
        "veil": "radial-gradient(circle at 16% 20%, rgba(255, 193, 166, 0.34), transparent 24%), radial-gradient(circle at 80% 30%, rgba(255, 239, 218, 0.48), transparent 26%), radial-gradient(circle at 50% 85%, rgba(255, 163, 147, 0.16), transparent 24%)",
        "accent": "#ffb191",
        "bubble": "rgba(255, 255, 255, 0.84)",
    },
    {
        "id": "signal-blue",
        "name": "信号海雾",
        "surface": "rgba(245, 251, 255, 0.54)",
        "veil": "radial-gradient(circle at 22% 18%, rgba(81, 184, 255, 0.28), transparent 26%), radial-gradient(circle at 78% 38%, rgba(160, 255, 240, 0.28), transparent 24%), radial-gradient(circle at 42% 78%, rgba(131, 155, 255, 0.18), transparent 24%)",
        "accent": "#53c2ff",
        "bubble": "rgba(255, 255, 255, 0.8)",
    },
    {
        "id": "sakura-net",
        "name": "樱色回线",
        "surface": "rgba(255, 248, 250, 0.58)",
        "veil": "radial-gradient(circle at 16% 22%, rgba(255, 187, 212, 0.34), transparent 24%), radial-gradient(circle at 74% 18%, rgba(255, 249, 252, 0.54), transparent 30%), radial-gradient(circle at 44% 84%, rgba(255, 150, 189, 0.16), transparent 22%)",
        "accent": "#ff94b5",
        "bubble": "rgba(255, 255, 255, 0.84)",
    },
]

API_ROUTES = [
    {"method": "GET", "path": "/api/health", "note": "检查本地后端是否在线"},
    {"method": "GET", "path": "/api/workspace/load", "note": "读取本地工作区快照"},
    {"method": "POST", "path": "/api/workspace/save", "note": "保存本地工作区快照"},
    {"method": "GET", "path": "/api/bootstrap", "note": "拉取初始化会话、智能体、动态与配置"},
    {"method": "GET", "path": "/api/workflows/{workflow_id}", "note": "查看某个任务的详细状态、graph 与 timeline"},
    {"method": "GET", "path": "/api/workflows/{workflow_id}/timeline", "note": "查看某个任务的 timeline 与 graph"},
    {"method": "GET", "path": "/api/actors/{actor_id}/skills", "note": "查看某个智能体当前可见的公有、特有与习得 Skill"},
    {"method": "GET", "path": "/api/tools/catalog", "note": "查看当前系统工具目录、授权工作区与各智能体工具可用性"},
    {"method": "GET", "path": "/api/system/inspect", "note": "查看系统总览，包含 Skill 与 Tool 的区别、当前配置和授权工作区"},
    {"method": "POST", "path": "/api/workflows/tick", "note": "手动推进一个任务执行 tick，便于本地调试与测试"},
    {"method": "GET", "path": "/api/skills/catalog", "note": "读取系统公有 Skill 目录"},
    {"method": "GET", "path": "/api/skills/proposals", "note": "读取公有 Skill 改进提案与审批结果"},
    {"method": "POST", "path": "/api/skills/proposals", "note": "提交公有 Skill 改进提案，等待用户审批"},
    {"method": "POST", "path": "/api/skills/preview", "note": "预览当前角色会如何选择并组合 Skill"},
    {"method": "POST", "path": "/api/skills/reload", "note": "重载系统公有 Skill 目录"},
    {"method": "POST", "path": "/api/conversations/open", "note": "打开会话并同步未读状态"},
    {"method": "POST", "path": "/api/messages/send", "note": "发送文本、任务或协作请求"},
    {"method": "POST", "path": "/api/workflows/dispatch", "note": "创建多智能体协作工作流"},
    {"method": "POST", "path": "/api/workflows/help-request", "note": "向编外智能体发起协助申请"},
    {"method": "POST", "path": "/api/agents/favorite", "note": "收藏或取消收藏智能体"},
    {"method": "POST", "path": "/api/conversations/background", "note": "切换聊天背景"},
    {"method": "POST", "path": "/api/groups/roles", "note": "更新群成员角色与权限"},
    {"method": "POST", "path": "/api/groups/lifecycle", "note": "决定协作频道完成后是保留闲聊还是解散"},
    {"method": "POST", "path": "/api/posts/like", "note": "切换朋友圈点赞"},
    {"method": "POST", "path": "/api/posts/comment", "note": "新增朋友圈评论"},
    {"method": "POST", "path": "/api/posts/publish", "note": "发布朋友圈动态"},
    {"method": "POST", "path": "/api/personas/preview", "note": "抓取角色资料并生成可编辑的人设草稿"},
    {"method": "POST", "path": "/api/personas/compose", "note": "根据角色名生成人设与 JUUS 账号"},
    {"method": "POST", "path": "/api/personas/apply", "note": "将编辑后的人设草稿应用到整个系统"},
    {"method": "POST", "path": "/api/system/reset", "note": "清空聊天、任务、动态和人设，恢复初始状态"},
    {"method": "POST", "path": "/api/window/preset", "note": "同步桌面窗口预设"},
    {"method": "POST", "path": "/api/tools/plan", "note": "生成工具执行计划并触发审批"},
    {"method": "POST", "path": "/api/tools/execute", "note": "执行已审批的本地工具动作"},
    {"method": "POST", "path": "/api/tools/undo", "note": "撤销最近一次可逆工具执行"},
    {"method": "POST", "path": "/api/approvals/resolve", "note": "秘书或用户处理审批请求"},
    {"method": "POST", "path": "/api/workflows/interrupt", "note": "用户插嘴更新任务上下文"},
    {"method": "GET", "path": "/ws", "note": "实时消息与事件通道"},
]

REALTIME_EVENTS = [
    "runtime.connected",
    "runtime.pong",
    "conversation.typing",
    "conversation.message.created",
    "conversation.message.updated",
    "workflow.created",
    "workflow.stage.changed",
    "workflow.review.requested",
    "workflow.review.resolved",
    "workflow.agent.help_requested",
    "workflow.skill.completed",
    "skill.proposal.created",
    "skill.proposal.resolved",
    "post.created",
    "post.comment.created",
    "tool.approval.requested",
    "tool.execution.completed",
]
